/** Renders a symbol from the inline sprite in index.html (generated by tools/fetch-assets.mjs). */
export function Icon({ name, className = 'icon' }: { name: string; className?: string }) {
  return (
    <svg className={className} aria-hidden="true">
      <use href={`#${name}`} />
    </svg>
  );
}
